sqlConnStr = "postgres://postgres:postgres@localhost/bloomapi?sslmode=disable"
searchHosts = [
  "localhost"
]
bloomapiPort = 3005
statsLogger = "syslog" # values can be: 'syslog' or 'stdout'
generalLogger = "syslog"